# docker-compose.yml

version: "3.7"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgressDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: stocks-6-sense
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - stocks-6-sense:/var/lib/postgresql/data

  stocks-6-sense:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
    depends_on:
      - postgres
    ports:
      - '8000:8000'
        
volumes:
  stocks-6-sense: